### ISSUE TITLE
Not Works

### ISSUE THREAD

**Issue by mthri** [blackcrw/wprecon#13]
Hi,
I try to use this app, but can't work for me
run it by following command `go run main -u [My URL]`
after several second got this message `[!] I'm not absolutely sure that this target is using wordpress! 37.50% chance. do you wish to continue ? [Y/n]:`
then i enter Y but app closed!

I use `go version go1.15.6 linux/amd64` on `Pop!_OS 20.10`

**Comment by ffx64** [comment]
In this version that is on github to be able to execute each function you need to inform the arguments/flags.
For example: `go run main -u https://xv.com/ --users-enumerate --plugins-enumerate`.

But I believe that at the latest by tomorrow a very large update will be available.
That will improve **wprecon** in this issue of flags/arguments.
