### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by sinlee1** [blackcrw/wprecon#19]
![image](https://user-images.githubusercontent.com/29684167/110612563-47548e00-81cb-11eb-89ea-a8027c8b8317.png)

**Comment by ffx64** [comment]
hello, as far as I could understand your Go compiler is very outdated. Try to update it...
I apologize for the delayed response.

**Comment by sinlee1** [comment]
![image](https://user-images.githubusercontent.com/29684167/110907688-ba374380-8348-11eb-8b6b-3ea70396d1da.png)

- The latest version of Go still has a problem
- Can I only use a specific version of Go?

**Comment by sinlee1** [comment]
- Update

 With Version Go 1.15, it works

**Comment by ffx64** [comment]
The Golang version that the wprecon is being written is 1.15...
