### ISSUE TITLE
go get github.com/blackbinn/wprecon: no matching versions for query "upgrade" HIGH SIERRA 

### ISSUE THREAD

**Issue by lillois59** [blackcrw/wprecon#20]
hey bro, 

how I can fix this issue on my MBP high sierra using go version go1.16.5 darwin/amd64 ?

merci

**Comment by ffx64** [comment]
Hop!
This is just an incompatibility of the version of golang that is on your computer with the version that wprecon is being developed.

**Comment by lillois59** [comment]
> Hop!
> This is just an incompatibility of the version of golang that is on your computer with the version that wprecon is being developed.
> 
> 
> ##### _Note: The development of wprecon was paused._
> #####

okay chef !

**Comment by ffx64** [comment]
Today, I was more calmly researching the subject... and I found something that corrected here when I tried to download the project with the `go get`.

Bash:
- `echo "GOPROXY=direct" >> ~/.bash_profile`

Zsh:
- `echo "GOPROXY=direct" >> ~/.zsh_profile`

`go clean -modcache`
