### ISSUE TITLE
Segmentation violation

### ISSUE THREAD

**Issue by RJSOG** [blackcrw/wprecon#21]
Hi, i was using wprecon to help me throught a pentest, but suddently wprecon stop 
OS: ArchLinux
Used Command : wprecon --url *url* --force --aggressive-mode --detection-waf --random-agent
After a few minutes of scan wprecon prints me :
"Get *url*/v1/api/vulnerable/plugins/elementor/5.11.0: dial tcp *IP* connect: connection timed out"
"panic: runtime error: invalid memory address or nil pointer dereference"
"[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc5852f]
and a stack trace !

Can you help me on that ?

**Comment by sven-hash** [comment]
I've this problem too, with command ` go run main.go -u https://example.com -v --aggressive-mode` 
Version: 1.6.5 alpha

Here's the stack trace:
```
[✗] Get http://144.217.235.104:8777//v1/api/vulnerable/plugins/wp-carousel-pro/3.1.4: dial tcp 144.217.235.104:8777: connect: connection timed out

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc5ef1f]

goroutine 1 [running]:
github.com/blackbinn/wprecon/cli/cmd.pluginvulnenum(0xc000989050, 0xf, 0xc00098907d, 0x5)
        /mnt/c/Users/ROUVSV/wprecon/cli/cmd/root.go:308 +0x6f
github.com/blackbinn/wprecon/cli/cmd.RootOptionsRun(0x176a840, 0xc000042400, 0x0, 0x4)
        /mnt/c/Users/ROUVSV/wprecon/cli/cmd/root.go:204 +0xca7
github.com/spf13/cobra.(*Command).execute(0x176a840, 0xc0000ca010, 0x4, 0x4, 0x176a840, 0xc0000ca010)
        /home/svenubuntu/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x176a840, 0x17955b0, 0xc0000a8058, 0x8)
        /home/svenubuntu/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/svenubuntu/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/blackbinn/wprecon/cli.Execute()
        /mnt/c/Users/ROUVSV/wprecon/cli/wprecon.go:34 +0x2d
main.main()
        /mnt/c/Users/ROUVSV/wprecon/main.go:12 +0x32
exit status 2
```

**Comment by ffx64** [comment]
There was an issue with the server where the API was hosted.
Therefore, I ended up losing all the data that were in it.

#### Note: A new version of wprecon has been released where these bugs have been removed. #22
